### ISSUE TITLE
Rails 3 support

### ISSUE THREAD

**Issue by iamnader** [wilkerlucio/mongoid_taggable#1]
Is this supported in Rails 3?  When I install as a gem and add include Mongoid::Taggable to my class I get this error:

/Users/nader/repo/napa/app/models/post.rb:4: uninitialized constant Mongoid::Taggable (NameError)
    from /Library/Ruby/Gems/1.8/gems/railties-3.0.0.beta4/lib/rails/engine.rb:138:in `eager_load!'
    from /Library/Ruby/Gems/1.8/gems/railties-3.0.0.beta4/lib/rails/engine.rb:137:in`each'
    from /Library/Ruby/Gems/1.8/gems/railties-3.0.0.beta4/lib/rails/engine.rb:137:in `eager_load!'
    from /Library/Ruby/Gems/1.8/gems/railties-3.0.0.beta4/lib/rails/engine.rb:135:in`each'

**Comment by wilkerlucio** [comment]
Thanks iamnader, fixed into gem version 0.1.1, please update the gem and it will be work fine

**Comment by iamnader** [comment]
awesome.  thanks for the quick turnaround.  confirmed fix.

**Comment by jurikern** [comment]
It not works for Rails 3.2.8 and Mongoid 3.0.1. 

Routing Error: uninitialized constant Mongoid::Taggable::Mongo. Gem version is 0.1.7.

**Comment by sairamc** [comment]
Any progress on this?
