### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by acechase** [wilkerlucio/mongoid_taggable#28]
Hi Wilker,

I see there's a number of outstanding pull requests on this project. Do you have plans to continue maintaining this? It looks like a very useful project, but I need mongoid 3 support and I'm wondering which fork I should point at...

Thanks!

**Comment by wilkerlucio** [comment]
hi guys, sorry, I'm not really maintaining this gem anymore, because I'm not having the chances to use Mongo on my current work, I'll be glad to give the repository to someone else that has interest to maintain it.

**Comment by astjohn** [comment]
@acechase, I'm a bit late to this thread, but I think I've tidied up the gem for mongoid 3. I've placed it on a [separate branch](https://github.com/astjohn/mongoid_taggable/tree/mongoid3) for the time being.

Let me know how it goes if you'd like. All the specs seem to be passing, but I'm still wary of the tag index feature.

**Comment by akshatpradhan** [comment]
+1, I'd like to use this gem

**Comment by calebjclark** [comment]
@wilkerlucio I'd love to take over the maintenance of this repository. We are heavily using this gem in our new Fanforce app.

**Comment by wilkerlucio** [comment]
@calebclark I added you as a collaborator on the repo, now you can work strait on this main repository ;)

**Comment by calebjclark** [comment]
The new 1.x version of Mongoid::Taggable now supports Mongoid 3.x.
