### ISSUE TITLE
uninitialized constant Mongoid::Taggable::Mongo

### ISSUE THREAD

**Issue by chada** [wilkerlucio/mongoid_taggable#29]
`mongoid-taggable` added to Gemfile and `Mongoid::Taggable` included in the model. 

Help me out, plz!

**Comment by chada** [comment]
figured out. mongoid_taggable doesn't support mongoid 3.x.

**Comment by calebjclark** [comment]
The new 1.x version of Mongoid::Taggable now supports Mongoid 3.x.
