### ISSUE TITLE
undefined method `master' for Mongoid::Config:Class

### ISSUE THREAD

**Issue by sunilrao** [wilkerlucio/mongoid_taggable#6]
Hi,
I followed the steps described by adding the gem, modifying the model and _form of my rails 3 mongoid based application but when I try to create a document with tags, I get the above error.  

I do get see the tags in the logs, but I am unable to create the document.  Here is the log

MONGODB hh_development['items'].insert([{"name"=>"item1", "description"=>"some items", "tags_array"=>["item one"], "_id"=>BSON::ObjectId('4d48f96bffef981382000001')}])

What am I missing?  

Thanks
Sunil

**Comment by wilkerlucio** [comment]
Hi sunilrao,

In last update we changed the config instance to work with newer versions of Mongoid. You are only on a version mismatch, to fix it please update your Mongoid version to latest one. If you can't update the Mongoid, downgrade the mongoid_taggable to version 0.1.1 and it will work :)

Please let me know if it work for you :)

**Comment by sunilrao** [comment]
WIlker,

Perfect. Thanks for the help.  I upgraded Mongoid.  It worked.

Thanks.
Sunil
